---
- hosts: webservers
  become: yes
  vars:
   - http_port: 8080
   - tomcat_version: 10.1.24

  tasks:
    - name: Run the apt get update
      apt:
        update_cache: yes

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jdk
        state: present

    - name: add user tomcat
      user:
        name: tomcat
        shell: /bin/false
        create_home: yes
        home: /opt/tomcat
    
    - name: add group tomcat
      group:
        name: tomcat
        state: present

    - name: Download Tomcat
      get_url:
        url: "https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.34/bin/apache-tomcat-10.1.34.tar.gz"
        dest: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
    
    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: /opt/tomcat
        remote_src: yes
        creates: /opt/tomcat/apache-tomcat-{{ tomcat_version }}
    
    - name: Set Permissions
      file: path=/opt/tomcat/apache-tomcat-{{ tomcat_version }} owner=tomcat group=tomcat state=directory recurse=yes

    - name: Run startup
      shell: nohup /opt/tomcat/apache-tomcat-10.1.34/bin/startup.sh
